/**
 *
 * @type {{RETURN_OK: string, RETURN_ERR: string, USER_STATUS_ACTIVE: number, USER_STATUS_FREEZED: number, USER_STATUS_BLOCKED: number, EMAIL_TYPE_NEW: number, EMAIL_TYPE_REGISTER: number, EMAIL_TYPE_EMAIL_CHANGE_REQUEST_FROM: number, EMAIL_TYPE_EMAIL_CHANGE_REQUEST_TO: number, OBJECT_STATUS_DRAFT: number, OBJECT_STATUS_MODERATION_PENDING: number, OBJECT_STATUS_REJECTED: number, OBJECT_STATUS_PUBLISHED: number, OBJECT_STATUS_ARCHIVED: number, RZ_CMP_V2_OBJECT_TYPE_FLAT: number, RZ_CMP_V2_OBJECT_TYPE_ROOM: number, RZ_CMP_V2_OBJECT_TYPE_HOUSE: number, RZ_CMP_V2_OBJECT_TYPE_COTTAGE: number, RZ_CMP_V2_OBJECT_TYPE_DACHA: number, RZ_CMP_V2_OBJECT_TYPE_TOWNHOUSE: number, RZ_CMP_V2_OBJECT_TYPE_HALF_HOUSE: number, RZ_CMP_V2_OBJECT_TYPE_LOT_IGS: number, RZ_CMP_V2_OBJECT_TYPE_LOT_GARDEN: number, RZ_CMP_V2_OBJECT_TYPE_LOT_FARM: number, RZ_CMP_V2_OBJECT_TYPE_GARAGE: number, RZ_CMP_V2_OBJECT_TYPE_GARAGE_PARKING_PLACE: number, RZ_CMP_V2_OBJECT_TYPE_GARAGE_BOX: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_OFFICE: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_RETAIL: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_FREE_PURPOSE: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_PUBLIC_CATERING: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_AUTO_REPAIR: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_BUSINESS: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_LEGAL_ADDRESS: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_LAND: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_HOTEL: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_WAREHOUSE: number, RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_MANUFACTURING: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_1_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_2_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_3_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_4_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_5_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_STUDIO_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_OPEN_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_ROOM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_COTTAGE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_DACHA_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_TOWNHOUSE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_HALF_HOUSE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_LOT_IGS_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_LOT_GARDEN_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_LOT_FARM_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_PARKING_PLACE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_BOX_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_OFFICE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_RETAIL_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_FREE_PURPOSE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_PUBLIC_CATERING_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_AUTO_REPAIR_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_BUSINESS_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_LAND_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_HOTEL_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_WAREHOUSE_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_MANUFACTURING_SALE: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_1_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_2_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_3_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_4_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_5_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_STUDIO_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_FLAT_OPEN_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_ROOM_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_COTTAGE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_DACHA_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_TOWNHOUSE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_HALF_HOUSE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_PARKING_PLACE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_BOX_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_OFFICE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_RETAIL_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_FREE_PURPOSE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_PUBLIC_CATERING_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_AUTO_REPAIR_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_BUSINESS_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_LEGAL_ADDRESS_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_LAND_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_HOTEL_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_WAREHOUSE_RENT: number, RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_MANUFACTURING_RENT: number, RZ_OBJECT_TYPE_FLAT: number, RZ_OBJECT_TYPE_ROOM: number, RZ_OBJECT_TYPE_HOUSE: number, RZ_OBJECT_TYPE_LAND: number, RZ_OBJECT_TYPE_GARAGE: number, RZ_OBJECT_TYPE_COMMERCIAL: number, RZ_OFFER_TYPE_SALE: number, RZ_OFFER_TYPE_RENT: number, RZ_RENT_TYPE_MON: number, RZ_RENT_TYPE_DAY: number, RZ_HOUSE_TYPE_HOUSE: number, RZ_HOUSE_TYPE_COTTAGE: number, RZ_HOUSE_TYPE_DACHA: number, RZ_HOUSE_TYPE_TOWNHOUSE: number, RZ_HOUSE_TYPE_HALF_HOUSE: number, RZ_TAXATION_FORM_TYPE_NDS: number, RZ_TAXATION_FORM_TYPE_USN: number, RZ_DEAL_STATUS_DIRECT_RENT: number, RZ_DEAL_STATUS_SUB_RENT: number, RZ_DEAL_STATUS_SALE_OF_LEASE_RIGHTS: number, RZ_LOT_TYPE_IGS: number, RZ_LOT_TYPE_GARDEN: number, RZ_LOT_TYPE_FARM: number, RZ_LOT_AREA_UNIT_AR: number, RZ_LOT_AREA_UNIT_GA: number, RZ_SHOWER_TYPE_INSIDE: number, RZ_SHOWER_TYPE_OUTSIDE: number, RZ_SHOWER_TYPE_NONE: number, RZ_TOILET_TYPE_INSIDE: number, RZ_TOILET_TYPE_OUTSIDE: number, RZ_TOILET_TYPE_NONE: number, RZ_BUILDING_TYPE_PANEL: number, RZ_BUILDING_TYPE_BRICK: number, RZ_BUILDING_TYPE_MONOLITHIC: number, RZ_PARKING_TYPE_SPONTANEOUS: number, RZ_PARKING_TYPE_SECURE: number, RZ_PARKING_TYPE_UNSECURE: number, RZ_PARKING_TYPE_UNDERGROUND: number, RZ_ROOMS_TYPE_ONE: number, RZ_ROOMS_TYPE_TWO: number, RZ_ROOMS_TYPE_THREE: number, RZ_ROOMS_TYPE_FOUR: number, RZ_ROOMS_TYPE_FIVE: number, RZ_ROOMS_TYPE_STUDIO: number, RZ_ROOMS_TYPE_OPEN: number, RZ_BATHROOM_TYPE_MATCHED: number, RZ_BATHROOM_TYPE_SEPARATED: number, RZ_BATHROOM_TYPE_TWO: number, RZ_BATHROOM_TYPE_THREE: number, RZ_BATHROOM_TYPE_FOUR_OR_MORE: number, RZ_BALCONY_TYPE_NONE: number, RZ_BALCONY_TYPE_BALCONY: number, RZ_BALCONY_TYPE_LOGGIA: number, RZ_FLOOR_COVERING_TYPE_CARPETING: number, RZ_FLOOR_COVERING_TYPE_LAMINATE: number, RZ_FLOOR_COVERING_TYPE_LINOLEUM: number, RZ_FLOOR_COVERING_TYPE_PARQUET: number, RZ_RENOVATION_TYPE_DESIGNER: number, RZ_RENOVATION_TYPE_EURO: number, RZ_RENOVATION_TYPE_TRIM: number, RZ_RENOVATION_TYPE_NEEDS: number, RZ_RENOVATION_TYPE_GOOD: number, RZ_RENOVATION_TYPE_PARTIAL: number, RZ_RENOVATION_TYPE_ROUGH_FINISH: number, RZ_GARAGE_TYPE_PARKING_PLACE: number, RZ_GARAGE_TYPE_GARAGE: number, RZ_GARAGE_TYPE_BOX: number, RZ_GARAGE_GARAGE_TYPE_BUILTIN: number, RZ_GARAGE_GARAGE_TYPE_CAPITAL: number, RZ_GARAGE_GARAGE_TYPE_SHELL: number, RZ_GARAGE_GARAGE_TYPE_SAMOSTROY: number, RZ_GARAGE_BOX_TYPE_BRICK: number, RZ_GARAGE_BOX_TYPE_METAL: number, RZ_GARAGE_STATUS_TYPE_COOPERATIVE: number, RZ_GARAGE_STATUS_TYPE_OWNERSHIP: number, RZ_GARAGE_STATUS_TYPE_BY_PROXY: number, RZ_GARAGE_PARKING_TYPE_ROOF: number, RZ_GARAGE_PARKING_TYPE_UNDERGROUND: number, RZ_GARAGE_PARKING_TYPE_GROUND: number, RZ_GARAGE_PARKING_TYPE_MULTILEVEL: number, RZ_GARAGE_PARKING_TYPE_OPEN: number, RZ_COMMERCIAL_TYPE_OFFICE: number, RZ_COMMERCIAL_TYPE_RETAIL: number, RZ_COMMERCIAL_TYPE_FREE_PURPOSE: number, RZ_COMMERCIAL_TYPE_PUBLIC_CATERING: number, RZ_COMMERCIAL_TYPE_AUTO_REPAIR: number, RZ_COMMERCIAL_TYPE_BUSINESS: number, RZ_COMMERCIAL_TYPE_LEGAL_ADDRESS: number, RZ_COMMERCIAL_TYPE_LAND: number, RZ_COMMERCIAL_TYPE_HOTEL: number, RZ_COMMERCIAL_TYPE_WAREHOUSE: number, RZ_COMMERCIAL_TYPE_MANUFACTURING: number, RZ_COMMERCIAL_BUILDING_TYPE_BUSINESS_CENTER: number, RZ_COMMERCIAL_BUILDING_TYPE_WAREHOUSE: number, RZ_COMMERCIAL_BUILDING_TYPE_SHOPPING_CENTER: number, RZ_COMMERCIAL_BUILDING_TYPE_DETACHED_BUILDING: number, RZ_COMMERCIAL_BUILDING_TYPE_RESIDENTIAL_BUILDING: number, RZ_COMMERCIAL_OFFICE_CLASS_A: number, RZ_COMMERCIAL_OFFICE_CLASS_A_PLUS: number, RZ_COMMERCIAL_OFFICE_CLASS_B: number, RZ_COMMERCIAL_OFFICE_CLASS_B_PLUS: number, RZ_COMMERCIAL_OFFICE_CLASS_C: number, RZ_COMMERCIAL_OFFICE_CLASS_C_PLUS: number, RZ_COMMERCIAL_ENTRANCE_TYPE_SEPARATE: number, RZ_COMMERCIAL_ENTRANCE_TYPE_COMMON: number, RZ_USER_AGENT_STRING: string}}
 */
module.exports = {
    RETURN_OK: 'OK',
    RETURN_ERR: 'NOK',

    USER_STATUS_ACTIVE: 1,
    USER_STATUS_FREEZED: 2,
    USER_STATUS_BLOCKED: 3,

    EMAIL_TYPE_NEW: 1,
    EMAIL_TYPE_REGISTER: 2,
    EMAIL_TYPE_EMAIL_CHANGE_REQUEST_FROM: 6,
    EMAIL_TYPE_EMAIL_CHANGE_REQUEST_TO: 7,

    OBJECT_STATUS_DRAFT: 1,
    OBJECT_STATUS_MODERATION_PENDING: 2,
    OBJECT_STATUS_REJECTED: 3,
    OBJECT_STATUS_PUBLISHED: 4,
    OBJECT_STATUS_ARCHIVED: 5,


    /** Object constants */

    /** COMPOUNDS */

    /** Compound object types v2 */
    RZ_CMP_V2_OBJECT_TYPE_FLAT: 1,
    RZ_CMP_V2_OBJECT_TYPE_ROOM: 2,
    RZ_CMP_V2_OBJECT_TYPE_HOUSE: 3,
    RZ_CMP_V2_OBJECT_TYPE_COTTAGE: 4,
    RZ_CMP_V2_OBJECT_TYPE_DACHA: 5,
    RZ_CMP_V2_OBJECT_TYPE_TOWNHOUSE: 6,
    RZ_CMP_V2_OBJECT_TYPE_HALF_HOUSE: 7,
    RZ_CMP_V2_OBJECT_TYPE_LOT_IGS: 8,
    RZ_CMP_V2_OBJECT_TYPE_LOT_GARDEN: 9,
    RZ_CMP_V2_OBJECT_TYPE_LOT_FARM: 10,
    RZ_CMP_V2_OBJECT_TYPE_GARAGE: 11,
    RZ_CMP_V2_OBJECT_TYPE_GARAGE_PARKING_PLACE: 12,
    RZ_CMP_V2_OBJECT_TYPE_GARAGE_BOX: 13,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_OFFICE: 14,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_RETAIL: 15,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_FREE_PURPOSE: 16,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_PUBLIC_CATERING: 17,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_AUTO_REPAIR: 18,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_BUSINESS: 19,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_LEGAL_ADDRESS: 20,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_LAND: 21,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_HOTEL: 22,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_WAREHOUSE: 23,
    RZ_CMP_V2_OBJECT_TYPE_COMMERCIAL_MANUFACTURING: 24,

    /** Mega compound object types */
    /** sale */
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_1_ROOM_SALE: 1,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_2_ROOM_SALE: 2,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_3_ROOM_SALE: 3,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_4_ROOM_SALE: 4,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_5_ROOM_SALE: 5,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_STUDIO_ROOM_SALE: 6,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_OPEN_ROOM_SALE: 7,

    RZ_MEGA_CMP_OBJECT_TYPE_ROOM_SALE: 8,

    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_SALE: 9,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_COTTAGE_SALE: 10,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_DACHA_SALE: 11,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_TOWNHOUSE_SALE: 12,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_HALF_HOUSE_SALE: 13,

    RZ_MEGA_CMP_OBJECT_TYPE_LOT_IGS_SALE: 14,
    RZ_MEGA_CMP_OBJECT_TYPE_LOT_GARDEN_SALE: 15,
    RZ_MEGA_CMP_OBJECT_TYPE_LOT_FARM_SALE: 16,

    RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_SALE: 17,
    RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_PARKING_PLACE_SALE: 18,
    RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_BOX_SALE: 19,

    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_OFFICE_SALE: 20,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_RETAIL_SALE: 21,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_FREE_PURPOSE_SALE: 22,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_PUBLIC_CATERING_SALE: 23,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_AUTO_REPAIR_SALE: 24,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_BUSINESS_SALE: 25,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_LAND_SALE: 26,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_HOTEL_SALE: 27,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_WAREHOUSE_SALE: 28,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_MANUFACTURING_SALE: 29,
    /** rent */
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_1_ROOM_RENT: 30,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_2_ROOM_RENT: 31,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_3_ROOM_RENT: 32,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_4_ROOM_RENT: 33,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_5_ROOM_RENT: 34,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_STUDIO_ROOM_RENT: 35,
    RZ_MEGA_CMP_OBJECT_TYPE_FLAT_OPEN_ROOM_RENT: 36,

    RZ_MEGA_CMP_OBJECT_TYPE_ROOM_RENT: 37,

    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_RENT: 38,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_COTTAGE_RENT: 39,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_DACHA_RENT: 40,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_TOWNHOUSE_RENT: 41,
    RZ_MEGA_CMP_OBJECT_TYPE_HOUSE_HALF_HOUSE_RENT: 42,

    RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_RENT: 43,
    RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_PARKING_PLACE_RENT: 44,
    RZ_MEGA_CMP_OBJECT_TYPE_GARAGE_BOX_RENT: 45,

    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_OFFICE_RENT: 46,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_RETAIL_RENT: 47,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_FREE_PURPOSE_RENT: 48,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_PUBLIC_CATERING_RENT: 49,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_AUTO_REPAIR_RENT: 50,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_BUSINESS_RENT: 51,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_LEGAL_ADDRESS_RENT: 52,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_LAND_RENT: 53,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_HOTEL_RENT: 54,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_WAREHOUSE_RENT: 55,
    RZ_MEGA_CMP_OBJECT_TYPE_COMMERCIAL_MANUFACTURING_RENT: 56,

    /** Object type */
    RZ_OBJECT_TYPE_FLAT: 1,                           // Квартира
    RZ_OBJECT_TYPE_ROOM: 2,                           // Комната
    RZ_OBJECT_TYPE_HOUSE: 3,                          // Дом/коттедж
    RZ_OBJECT_TYPE_LAND: 4,                           // Земля
    RZ_OBJECT_TYPE_GARAGE: 5,                         // Гараж
    RZ_OBJECT_TYPE_COMMERCIAL: 6,                     // Коммерческая

    /** Offer type */
    RZ_OFFER_TYPE_SALE: 1,                            // Продажа
    RZ_OFFER_TYPE_RENT: 2,                            // Аренда

    /** Offer type */
    RZ_RENT_TYPE_MON: 1,
    RZ_RENT_TYPE_DAY: 2,

    /** House type */
    RZ_HOUSE_TYPE_HOUSE: 1,                           // Дом
    RZ_HOUSE_TYPE_COTTAGE: 2,                         // Коттедж
    RZ_HOUSE_TYPE_DACHA: 3,                           // Дача
    RZ_HOUSE_TYPE_TOWNHOUSE: 4,                       // Таунхаус
    RZ_HOUSE_TYPE_HALF_HOUSE: 5,                      // Часть дома

    /** Taxation Form type */
    RZ_TAXATION_FORM_TYPE_NDS: 1,                     // НДС
    RZ_TAXATION_FORM_TYPE_USN: 2,                     // УСН

    /** Deal Status type */
    RZ_DEAL_STATUS_DIRECT_RENT: 1,                    // Прямая аренда
    RZ_DEAL_STATUS_SUB_RENT: 2,                       // Субаренда
    RZ_DEAL_STATUS_SALE_OF_LEASE_RIGHTS: 3,           // Продажа права аренды

    /** Lot type */
    RZ_LOT_TYPE_IGS: 1,                               // ИЖС
    RZ_LOT_TYPE_GARDEN: 2,                            // В садоводстве
    RZ_LOT_TYPE_FARM: 3,                              // Фермерский

    /** Lot type */
    RZ_LOT_AREA_UNIT_AR: 1,                           // Соток
    RZ_LOT_AREA_UNIT_GA: 2,                           // Гектар

    /** Shower type */
    RZ_SHOWER_TYPE_INSIDE: 1,                         // В доме
    RZ_SHOWER_TYPE_OUTSIDE: 2,                        // На улице
    RZ_SHOWER_TYPE_NONE: 3,                           // Отсутствует

    /** Toilet type */
    RZ_TOILET_TYPE_INSIDE: 1,                         // В доме
    RZ_TOILET_TYPE_OUTSIDE: 2,                        // На улице
    RZ_TOILET_TYPE_NONE: 3,                           // Отсутствует

    /** Building type */
    RZ_BUILDING_TYPE_PANEL: 1,                        // Панельный
    RZ_BUILDING_TYPE_BRICK: 2,                        // Кирпичный
    RZ_BUILDING_TYPE_MONOLITHIC: 3,                   // Монолитный

    /** Parking type */
    RZ_PARKING_TYPE_SPONTANEOUS: 1,                   // Стихийная
    RZ_PARKING_TYPE_SECURE: 2,                        // Охраняемая
    RZ_PARKING_TYPE_UNSECURE: 3,                      // Неохраняемая
    RZ_PARKING_TYPE_UNDERGROUND: 4,                   // Подземная

    /** Rooms type */
    RZ_ROOMS_TYPE_ONE: 1,                             // 1
    RZ_ROOMS_TYPE_TWO: 2,                             // 2
    RZ_ROOMS_TYPE_THREE: 3,                           // 3
    RZ_ROOMS_TYPE_FOUR: 4,                            // 4
    RZ_ROOMS_TYPE_FIVE: 5,                            // 5
    RZ_ROOMS_TYPE_STUDIO: 6,                          // Студия
    RZ_ROOMS_TYPE_OPEN: 7,                            // Свободная планировка

    /** Bathroom type */
    RZ_BATHROOM_TYPE_MATCHED: 1,                      // Совмещенный
    RZ_BATHROOM_TYPE_SEPARATED: 2,                    // Раздельный
    RZ_BATHROOM_TYPE_TWO: 3,                          // 2
    RZ_BATHROOM_TYPE_THREE: 4,                        // 3
    RZ_BATHROOM_TYPE_FOUR_OR_MORE: 5,                 // 4+

    /** Balcony type */
    RZ_BALCONY_TYPE_NONE: 0,                          // Нет
    RZ_BALCONY_TYPE_BALCONY: 1,                       // Балкон
    RZ_BALCONY_TYPE_LOGGIA: 2,                        // Лоджия

    /** Floor covering type */
    RZ_FLOOR_COVERING_TYPE_CARPETING: 1,              // Ковролин
    RZ_FLOOR_COVERING_TYPE_LAMINATE: 2,               // Ламинат
    RZ_FLOOR_COVERING_TYPE_LINOLEUM: 3,               // Линолеум
    RZ_FLOOR_COVERING_TYPE_PARQUET: 4,                // Паркет

    /** Renovation type */
    RZ_RENOVATION_TYPE_DESIGNER: 1,                   // дизайнерский
    RZ_RENOVATION_TYPE_EURO: 2,                       // евро
    RZ_RENOVATION_TYPE_TRIM: 3,                       // с отделкой
    RZ_RENOVATION_TYPE_NEEDS: 4,                      // требует ремонта
    RZ_RENOVATION_TYPE_GOOD: 5,                       // хороший
    RZ_RENOVATION_TYPE_PARTIAL: 6,                    // частичный ремонт
    RZ_RENOVATION_TYPE_ROUGH_FINISH: 7,               // черновая отделка

    /** Garage type */
    RZ_GARAGE_TYPE_PARKING_PLACE: 1,                  // Машиноместо
    RZ_GARAGE_TYPE_GARAGE: 2,                         // Гараж
    RZ_GARAGE_TYPE_BOX: 3,                            // Бокс

    /** Garage Garage type */
    RZ_GARAGE_GARAGE_TYPE_BUILTIN: 1,                 // Встроенный
    RZ_GARAGE_GARAGE_TYPE_CAPITAL: 2,                 // Капитальный
    RZ_GARAGE_GARAGE_TYPE_SHELL: 3,                   // Ракушка
    RZ_GARAGE_GARAGE_TYPE_SAMOSTROY: 4,               // Самострой

    /** Garage Box type */
    RZ_GARAGE_BOX_TYPE_BRICK: 1,                      // Кирпичный
    RZ_GARAGE_BOX_TYPE_METAL: 2,                      // Металличесикй

    /** Garage status type */
    RZ_GARAGE_STATUS_TYPE_COOPERATIVE: 1,             // Кооператив
    RZ_GARAGE_STATUS_TYPE_OWNERSHIP: 2,               // Собственность
    RZ_GARAGE_STATUS_TYPE_BY_PROXY: 3,                // По доверенности

    /** Garage parking type */
    RZ_GARAGE_PARKING_TYPE_ROOF: 1,                   // На крыше
    RZ_GARAGE_PARKING_TYPE_UNDERGROUND: 2,            // Подземная
    RZ_GARAGE_PARKING_TYPE_GROUND: 3,                 // Наземная
    RZ_GARAGE_PARKING_TYPE_MULTILEVEL: 4,             // Многоуровневая
    RZ_GARAGE_PARKING_TYPE_OPEN: 5,                   // Открытая

    /** Commercial type */
    RZ_COMMERCIAL_TYPE_OFFICE: 1,                     // Офисное помещение
    RZ_COMMERCIAL_TYPE_RETAIL: 2,                     // Торговое помещение
    RZ_COMMERCIAL_TYPE_FREE_PURPOSE: 3,               // Помещение свободного назначения
    RZ_COMMERCIAL_TYPE_PUBLIC_CATERING: 4,            // Общепит
    RZ_COMMERCIAL_TYPE_AUTO_REPAIR: 5,                // Автосервис
    RZ_COMMERCIAL_TYPE_BUSINESS: 6,                   // Готовый бизнес
    RZ_COMMERCIAL_TYPE_LEGAL_ADDRESS: 7,              // Юридический адрес
    RZ_COMMERCIAL_TYPE_LAND: 8,                       // Земельный участок
    RZ_COMMERCIAL_TYPE_HOTEL: 9,                      // Гостиница
    RZ_COMMERCIAL_TYPE_WAREHOUSE: 10,                 // Складское помещение
    RZ_COMMERCIAL_TYPE_MANUFACTURING: 11,             // Производственное помещение

    /** Commercial building type */
    RZ_COMMERCIAL_BUILDING_TYPE_BUSINESS_CENTER: 1,      // Бизнес-центр
    RZ_COMMERCIAL_BUILDING_TYPE_WAREHOUSE: 2,            // Складской комплекс
    RZ_COMMERCIAL_BUILDING_TYPE_SHOPPING_CENTER: 3,      // Торговый центр
    RZ_COMMERCIAL_BUILDING_TYPE_DETACHED_BUILDING: 4,    // Отдельно стоящее здание
    RZ_COMMERCIAL_BUILDING_TYPE_RESIDENTIAL_BUILDING: 5, // Встроенное помещение, жилой дом

    /** Commercial building type */
    RZ_COMMERCIAL_OFFICE_CLASS_A: 1,                  // A
    RZ_COMMERCIAL_OFFICE_CLASS_A_PLUS: 2,             // A+
    RZ_COMMERCIAL_OFFICE_CLASS_B: 3,                  // B
    RZ_COMMERCIAL_OFFICE_CLASS_B_PLUS: 4,             // B+
    RZ_COMMERCIAL_OFFICE_CLASS_C: 5,                  // C
    RZ_COMMERCIAL_OFFICE_CLASS_C_PLUS: 6,             // C+

    /** Commercial entrance type */
    RZ_COMMERCIAL_ENTRANCE_TYPE_SEPARATE: 1,          // Отдельный
    RZ_COMMERCIAL_ENTRANCE_TYPE_COMMON: 2,            // Общий

    RZ_USER_AGENT_STRING: 'Realza Crawler v1.0.0.'

};
